# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BasicViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Viewer(object):
    def setupUi(self, Viewer):
        Viewer.setObjectName("Viewer")
        Viewer.resize(1138, 798)
        self.centralwidget = QtWidgets.QWidget(Viewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainGridLayout = QtWidgets.QGridLayout()
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setInteractive(True)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView.setRubberBandSelectionMode(QtCore.Qt.ContainsItemShape)
        self.graphicsView.setObjectName("graphicsView")
        self.mainGridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.mainGridLayout, 0, 0, 1, 1)
        Viewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Viewer)
        self.statusbar.setObjectName("statusbar")
        Viewer.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Viewer)
        self.toolBar.setObjectName("toolBar")
        Viewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(Viewer)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../../../../0_PYTHON_27/3_LSAT_TOOLBOX/ImagePNG/MonteCarlo2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(Viewer)
        self.actionExit.setIconVisibleInMenu(False)
        self.actionExit.setObjectName("actionExit")
        self.actionContent_window = QtWidgets.QAction(Viewer)
        self.actionContent_window.setCheckable(True)
        self.actionContent_window.setChecked(True)
        self.actionContent_window.setObjectName("actionContent_window")

        self.retranslateUi(Viewer)
        QtCore.QMetaObject.connectSlotsByName(Viewer)

    def retranslateUi(self, Viewer):
        _translate = QtCore.QCoreApplication.translate
        Viewer.setWindowTitle(_translate("Viewer", "Geodata Viewer"))
        self.toolBar.setWindowTitle(_translate("Viewer", "toolBar"))
        self.actionOpen.setText(_translate("Viewer", "Open..."))
        self.actionExit.setText(_translate("Viewer", "Exit..."))
        self.actionExit.setToolTip(_translate("Viewer", "Close the application"))
        self.actionContent_window.setText(_translate("Viewer", "Content window..."))
