# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddField.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddField(object):
    def setupUi(self, AddField):
        AddField.setObjectName("AddField")
        AddField.resize(264, 131)
        self.gridLayout = QtWidgets.QGridLayout(AddField)
        self.gridLayout.setObjectName("gridLayout")
        self.fieldTypeLabel = QtWidgets.QLabel(AddField)
        self.fieldTypeLabel.setObjectName("fieldTypeLabel")
        self.gridLayout.addWidget(self.fieldTypeLabel, 2, 0, 1, 2)
        self.fieldNameLineEdit = QtWidgets.QLineEdit(AddField)
        self.fieldNameLineEdit.setObjectName("fieldNameLineEdit")
        self.gridLayout.addWidget(self.fieldNameLineEdit, 1, 0, 1, 2)
        self.fieldNameLabel = QtWidgets.QLabel(AddField)
        self.fieldNameLabel.setObjectName("fieldNameLabel")
        self.gridLayout.addWidget(self.fieldNameLabel, 0, 0, 1, 2)
        self.fieldTypeComboBox = QtWidgets.QComboBox(AddField)
        self.fieldTypeComboBox.setObjectName("fieldTypeComboBox")
        self.fieldTypeComboBox.addItem("")
        self.fieldTypeComboBox.addItem("")
        self.fieldTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.fieldTypeComboBox, 3, 0, 1, 2)
        self.applyPushButton = QtWidgets.QPushButton(AddField)
        self.applyPushButton.setObjectName("applyPushButton")
        self.gridLayout.addWidget(self.applyPushButton, 4, 0, 1, 1)
        self.cancelPushButton = QtWidgets.QPushButton(AddField)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.gridLayout.addWidget(self.cancelPushButton, 4, 1, 1, 1)

        self.retranslateUi(AddField)
        QtCore.QMetaObject.connectSlotsByName(AddField)
        AddField.setTabOrder(self.fieldNameLineEdit, self.fieldTypeComboBox)
        AddField.setTabOrder(self.fieldTypeComboBox, self.applyPushButton)
        AddField.setTabOrder(self.applyPushButton, self.cancelPushButton)

    def retranslateUi(self, AddField):
        _translate = QtCore.QCoreApplication.translate
        AddField.setWindowTitle(_translate("AddField", "Dialog"))
        self.fieldTypeLabel.setText(_translate("AddField", "Field Type"))
        self.fieldNameLabel.setText(_translate("AddField", "Field Name"))
        self.fieldTypeComboBox.setItemText(0, _translate("AddField", "Double"))
        self.fieldTypeComboBox.setItemText(1, _translate("AddField", "Integer"))
        self.fieldTypeComboBox.setItemText(2, _translate("AddField", "Text"))
        self.applyPushButton.setText(_translate("AddField", "Apply"))
        self.cancelPushButton.setText(_translate("AddField", "Cancel"))
