# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PointBiserial.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PointBiserial(object):
    def setupUi(self, PointBiserial):
        PointBiserial.setObjectName("PointBiserial")
        PointBiserial.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PointBiserial)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.inputGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.inputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inventoryComboBox = QtWidgets.QComboBox(self.inputGroupBox)
        self.inventoryComboBox.setObjectName("inventoryComboBox")
        self.horizontalLayout.addWidget(self.inventoryComboBox)
        self.inventoryToolButton = QtWidgets.QToolButton(self.inputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inventoryToolButton.sizePolicy().hasHeightForWidth())
        self.inventoryToolButton.setSizePolicy(sizePolicy)
        self.inventoryToolButton.setObjectName("inventoryToolButton")
        self.horizontalLayout.addWidget(self.inventoryToolButton)
        self.label_2 = QtWidgets.QLabel(self.inputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.parameterComboBox = QtWidgets.QComboBox(self.inputGroupBox)
        self.parameterComboBox.setObjectName("parameterComboBox")
        self.horizontalLayout.addWidget(self.parameterComboBox)
        self.parameterToolButton = QtWidgets.QToolButton(self.inputGroupBox)
        self.parameterToolButton.setObjectName("parameterToolButton")
        self.horizontalLayout.addWidget(self.parameterToolButton)
        self.verticalLayout.addWidget(self.inputGroupBox)
        self.plotGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotGroupBox.sizePolicy().hasHeightForWidth())
        self.plotGroupBox.setSizePolicy(sizePolicy)
        self.plotGroupBox.setObjectName("plotGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.plotGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotFrame = QtWidgets.QFrame(self.plotGroupBox)
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.horizontalLayout_2.addWidget(self.plotFrame)
        self.verticalLayout.addWidget(self.plotGroupBox)
        self.applyPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.applyPushButton.setObjectName("applyPushButton")
        self.verticalLayout.addWidget(self.applyPushButton)
        PointBiserial.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PointBiserial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        PointBiserial.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PointBiserial)
        self.statusbar.setObjectName("statusbar")
        PointBiserial.setStatusBar(self.statusbar)

        self.retranslateUi(PointBiserial)
        QtCore.QMetaObject.connectSlotsByName(PointBiserial)

    def retranslateUi(self, PointBiserial):
        _translate = QtCore.QCoreApplication.translate
        PointBiserial.setWindowTitle(_translate("PointBiserial", "Point-biserial Correlation"))
        self.inputGroupBox.setTitle(_translate("PointBiserial", "Input"))
        self.label.setText(_translate("PointBiserial", "Inventory:"))
        self.inventoryToolButton.setText(_translate("PointBiserial", "..."))
        self.label_2.setText(_translate("PointBiserial", "Parameter:"))
        self.parameterToolButton.setText(_translate("PointBiserial", "..."))
        self.plotGroupBox.setTitle(_translate("PointBiserial", "Plot"))
        self.applyPushButton.setText(_translate("PointBiserial", "Apply"))
