# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ResultsPairDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContingencyResults(object):
    def setupUi(self, ContingencyResults):
        ContingencyResults.setObjectName("ContingencyResults")
        ContingencyResults.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(ContingencyResults)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.frequencyTab = QtWidgets.QWidget()
        self.frequencyTab.setObjectName("frequencyTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frequencyTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frequencyTabGridLayout = QtWidgets.QGridLayout()
        self.frequencyTabGridLayout.setObjectName("frequencyTabGridLayout")
        self.frequencyTableView = QtWidgets.QTableView(self.frequencyTab)
        self.frequencyTableView.setObjectName("frequencyTableView")
        self.frequencyTabGridLayout.addWidget(self.frequencyTableView, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.frequencyTabGridLayout)
        self.mainTabWidget.addTab(self.frequencyTab, "")
        self.chi2Tab = QtWidgets.QWidget()
        self.chi2Tab.setObjectName("chi2Tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.chi2Tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chi2TabGridLayout = QtWidgets.QGridLayout()
        self.chi2TabGridLayout.setObjectName("chi2TabGridLayout")
        self.chi2TableView = QtWidgets.QTableView(self.chi2Tab)
        self.chi2TableView.setObjectName("chi2TableView")
        self.chi2TabGridLayout.addWidget(self.chi2TableView, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.chi2TabGridLayout)
        self.mainTabWidget.addTab(self.chi2Tab, "")
        self.phiTab = QtWidgets.QWidget()
        self.phiTab.setObjectName("phiTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.phiTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.phiTabGridLayout = QtWidgets.QGridLayout()
        self.phiTabGridLayout.setObjectName("phiTabGridLayout")
        self.phiTableView = QtWidgets.QTableView(self.phiTab)
        self.phiTableView.setObjectName("phiTableView")
        self.phiTabGridLayout.addWidget(self.phiTableView, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.phiTabGridLayout)
        self.mainTabWidget.addTab(self.phiTab, "")
        self.horizontalLayout_5.addWidget(self.mainTabWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        ContingencyResults.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ContingencyResults)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        ContingencyResults.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ContingencyResults)
        self.statusbar.setObjectName("statusbar")
        ContingencyResults.setStatusBar(self.statusbar)

        self.retranslateUi(ContingencyResults)
        self.mainTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ContingencyResults)
        ContingencyResults.setTabOrder(self.mainTabWidget, self.frequencyTableView)
        ContingencyResults.setTabOrder(self.frequencyTableView, self.chi2TableView)
        ContingencyResults.setTabOrder(self.chi2TableView, self.phiTableView)

    def retranslateUi(self, ContingencyResults):
        _translate = QtCore.QCoreApplication.translate
        ContingencyResults.setWindowTitle(_translate("ContingencyResults", "Results - Contingency Analysis"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.frequencyTab), _translate("ContingencyResults", "Frequency table"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.chi2Tab), _translate("ContingencyResults", "X²"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.phiTab), _translate("ContingencyResults", "Phi (2x2)"))
