# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tabbedResultViewerAHP.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabbedResultViewerAHP(object):
    def setupUi(self, tabbedResultViewerAHP):
        tabbedResultViewerAHP.setObjectName("tabbedResultViewerAHP")
        tabbedResultViewerAHP.resize(1000, 750)
        tabbedResultViewerAHP.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(tabbedResultViewerAHP)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.modelTab = QtWidgets.QWidget()
        self.modelTab.setObjectName("modelTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.modelTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.smallTabWidget = QtWidgets.QTabWidget(self.modelTab)
        self.smallTabWidget.setObjectName("smallTabWidget")
        self.generalinformation = QtWidgets.QWidget()
        self.generalinformation.setObjectName("generalinformation")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.generalinformation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.modelTreeWidget = QtWidgets.QTreeWidget(self.generalinformation)
        self.modelTreeWidget.setObjectName("modelTreeWidget")
        self.verticalLayout_3.addWidget(self.modelTreeWidget)
        self.smallTabWidget.addTab(self.generalinformation, "")
        self.coefficientprios = QtWidgets.QWidget()
        self.coefficientprios.setObjectName("coefficientprios")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.coefficientprios)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.coefficientPriosTableWidget = QtWidgets.QTableWidget(self.coefficientprios)
        self.coefficientPriosTableWidget.setObjectName("coefficientPriosTableWidget")
        self.coefficientPriosTableWidget.setColumnCount(3)
        self.coefficientPriosTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.coefficientPriosTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coefficientPriosTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coefficientPriosTableWidget.setHorizontalHeaderItem(2, item)
        self.coefficientPriosTableWidget.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.coefficientPriosTableWidget)
        self.smallTabWidget.addTab(self.coefficientprios, "")
        self.pairwiserastercomp = QtWidgets.QWidget()
        self.pairwiserastercomp.setObjectName("pairwiserastercomp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pairwiserastercomp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pairwiseRasterCompTableWidget = QtWidgets.QTableWidget(self.pairwiserastercomp)
        self.pairwiseRasterCompTableWidget.setObjectName("pairwiseRasterCompTableWidget")
        self.pairwiseRasterCompTableWidget.setColumnCount(0)
        self.pairwiseRasterCompTableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.pairwiseRasterCompTableWidget)
        self.smallTabWidget.addTab(self.pairwiserastercomp, "")
        self.verticalLayout_2.addWidget(self.smallTabWidget)
        self.tabWidget.addTab(self.modelTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        tabbedResultViewerAHP.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tabbedResultViewerAHP)
        self.statusbar.setObjectName("statusbar")
        tabbedResultViewerAHP.setStatusBar(self.statusbar)

        self.retranslateUi(tabbedResultViewerAHP)
        self.tabWidget.setCurrentIndex(0)
        self.smallTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabbedResultViewerAHP)

    def retranslateUi(self, tabbedResultViewerAHP):
        _translate = QtCore.QCoreApplication.translate
        tabbedResultViewerAHP.setWindowTitle(_translate("tabbedResultViewerAHP", "MainWindow"))
        self.modelTreeWidget.headerItem().setText(0, _translate("tabbedResultViewerAHP", "Info"))
        self.modelTreeWidget.headerItem().setText(1, _translate("tabbedResultViewerAHP", "Value"))
        self.smallTabWidget.setTabText(self.smallTabWidget.indexOf(self.generalinformation), _translate("tabbedResultViewerAHP", "General Information"))
        item = self.coefficientPriosTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("tabbedResultViewerAHP", "Raster"))
        item = self.coefficientPriosTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("tabbedResultViewerAHP", "Value"))
        item = self.coefficientPriosTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("tabbedResultViewerAHP", "Coefficient Priority"))
        self.smallTabWidget.setTabText(self.smallTabWidget.indexOf(self.coefficientprios), _translate("tabbedResultViewerAHP", "Coefficient priorites"))
        self.smallTabWidget.setTabText(self.smallTabWidget.indexOf(self.pairwiserastercomp), _translate("tabbedResultViewerAHP", "Pairwise raster comparison"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modelTab), _translate("tabbedResultViewerAHP", "Seite"))
