# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tabbedResultViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabbedResultViewer(object):
    def setupUi(self, tabbedResultViewer):
        tabbedResultViewer.setObjectName("tabbedResultViewer")
        tabbedResultViewer.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(tabbedResultViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.modelTab = QtWidgets.QWidget()
        self.modelTab.setObjectName("modelTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.modelTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modelTreeWidget = QtWidgets.QTreeWidget(self.modelTab)
        self.modelTreeWidget.setObjectName("modelTreeWidget")
        self.verticalLayout_2.addWidget(self.modelTreeWidget)
        self.tabWidget.addTab(self.modelTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        tabbedResultViewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tabbedResultViewer)
        self.statusbar.setObjectName("statusbar")
        tabbedResultViewer.setStatusBar(self.statusbar)

        self.retranslateUi(tabbedResultViewer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabbedResultViewer)

    def retranslateUi(self, tabbedResultViewer):
        _translate = QtCore.QCoreApplication.translate
        tabbedResultViewer.setWindowTitle(_translate("tabbedResultViewer", "MainWindow"))
        self.modelTreeWidget.headerItem().setText(0, _translate("tabbedResultViewer", "Info"))
        self.modelTreeWidget.headerItem().setText(1, _translate("tabbedResultViewer", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modelTab), _translate("tabbedResultViewer", "Seite"))
