# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Hillshade.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hillshade(object):
    def setupUi(self, Hillshade):
        Hillshade.setObjectName("Hillshade")
        Hillshade.resize(418, 493)
        self.centralwidget = QtWidgets.QWidget(Hillshade)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainGridLayout = QtWidgets.QGridLayout()
        self.mainGridLayout.setObjectName("mainGridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainGridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.inputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.inputGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputGroupBoxGridLayout = QtWidgets.QGridLayout()
        self.inputGroupBoxGridLayout.setObjectName("inputGroupBoxGridLayout")
        self.demRasterLabel = QtWidgets.QLabel(self.inputGroupBox)
        self.demRasterLabel.setObjectName("demRasterLabel")
        self.inputGroupBoxGridLayout.addWidget(self.demRasterLabel, 0, 0, 1, 1)
        self.demRasterToolButton = QtWidgets.QToolButton(self.inputGroupBox)
        self.demRasterToolButton.setObjectName("demRasterToolButton")
        self.inputGroupBoxGridLayout.addWidget(self.demRasterToolButton, 1, 1, 1, 1)
        self.demRasterComboBox = QtWidgets.QComboBox(self.inputGroupBox)
        self.demRasterComboBox.setObjectName("demRasterComboBox")
        self.inputGroupBoxGridLayout.addWidget(self.demRasterComboBox, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.inputGroupBoxGridLayout)
        self.mainGridLayout.addWidget(self.inputGroupBox, 0, 0, 1, 4)
        self.okPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.okPushButton.setObjectName("okPushButton")
        self.mainGridLayout.addWidget(self.okPushButton, 3, 2, 1, 1)
        self.optionsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.optionsGroupBox.setObjectName("optionsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.optionsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.optionsGroupBoxGridLayout = QtWidgets.QGridLayout()
        self.optionsGroupBoxGridLayout.setObjectName("optionsGroupBoxGridLayout")
        self.altitudeLineEdit = QtWidgets.QLineEdit(self.optionsGroupBox)
        self.altitudeLineEdit.setObjectName("altitudeLineEdit")
        self.optionsGroupBoxGridLayout.addWidget(self.altitudeLineEdit, 3, 0, 1, 1)
        self.altitudeLabel = QtWidgets.QLabel(self.optionsGroupBox)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.optionsGroupBoxGridLayout.addWidget(self.altitudeLabel, 2, 0, 1, 1)
        self.azimuthLabel = QtWidgets.QLabel(self.optionsGroupBox)
        self.azimuthLabel.setObjectName("azimuthLabel")
        self.optionsGroupBoxGridLayout.addWidget(self.azimuthLabel, 0, 0, 1, 1)
        self.azimuthLineEdit = QtWidgets.QLineEdit(self.optionsGroupBox)
        self.azimuthLineEdit.setObjectName("azimuthLineEdit")
        self.optionsGroupBoxGridLayout.addWidget(self.azimuthLineEdit, 1, 0, 1, 1)
        self.zFactorLabel = QtWidgets.QLabel(self.optionsGroupBox)
        self.zFactorLabel.setObjectName("zFactorLabel")
        self.optionsGroupBoxGridLayout.addWidget(self.zFactorLabel, 4, 0, 1, 1)
        self.zFactorLineEdit = QtWidgets.QLineEdit(self.optionsGroupBox)
        self.zFactorLineEdit.setObjectName("zFactorLineEdit")
        self.optionsGroupBoxGridLayout.addWidget(self.zFactorLineEdit, 5, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.optionsGroupBoxGridLayout)
        self.mainGridLayout.addWidget(self.optionsGroupBox, 1, 0, 1, 4)
        self.outputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.outputGroupBox.setObjectName("outputGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.outputGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputGroupBoxGridLayout = QtWidgets.QGridLayout()
        self.outputGroupBoxGridLayout.setObjectName("outputGroupBoxGridLayout")
        self.outputRasterLineEdit = QtWidgets.QLineEdit(self.outputGroupBox)
        self.outputRasterLineEdit.setObjectName("outputRasterLineEdit")
        self.outputGroupBoxGridLayout.addWidget(self.outputRasterLineEdit, 1, 0, 1, 1)
        self.outputRasterLabel = QtWidgets.QLabel(self.outputGroupBox)
        self.outputRasterLabel.setObjectName("outputRasterLabel")
        self.outputGroupBoxGridLayout.addWidget(self.outputRasterLabel, 0, 0, 1, 1)
        self.outputRasterToolButton = QtWidgets.QToolButton(self.outputGroupBox)
        self.outputRasterToolButton.setObjectName("outputRasterToolButton")
        self.outputGroupBoxGridLayout.addWidget(self.outputRasterToolButton, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.outputGroupBoxGridLayout)
        self.mainGridLayout.addWidget(self.outputGroupBox, 2, 0, 1, 4)
        self.cancelPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.mainGridLayout.addWidget(self.cancelPushButton, 3, 1, 1, 1)
        self.mainGridLayout.setRowStretch(0, 1)
        self.mainGridLayout.setRowStretch(1, 2)
        self.mainGridLayout.setRowStretch(2, 1)
        self.verticalLayout.addLayout(self.mainGridLayout)
        Hillshade.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hillshade)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 21))
        self.menubar.setObjectName("menubar")
        Hillshade.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hillshade)
        self.statusbar.setObjectName("statusbar")
        Hillshade.setStatusBar(self.statusbar)

        self.retranslateUi(Hillshade)
        QtCore.QMetaObject.connectSlotsByName(Hillshade)
        Hillshade.setTabOrder(self.demRasterComboBox, self.demRasterToolButton)
        Hillshade.setTabOrder(self.demRasterToolButton, self.azimuthLineEdit)
        Hillshade.setTabOrder(self.azimuthLineEdit, self.altitudeLineEdit)
        Hillshade.setTabOrder(self.altitudeLineEdit, self.zFactorLineEdit)
        Hillshade.setTabOrder(self.zFactorLineEdit, self.outputRasterLineEdit)
        Hillshade.setTabOrder(self.outputRasterLineEdit, self.outputRasterToolButton)
        Hillshade.setTabOrder(self.outputRasterToolButton, self.okPushButton)

    def retranslateUi(self, Hillshade):
        _translate = QtCore.QCoreApplication.translate
        Hillshade.setWindowTitle(_translate("Hillshade", "MainWindow"))
        self.inputGroupBox.setTitle(_translate("Hillshade", "Input "))
        self.demRasterLabel.setText(_translate("Hillshade", "DEM raster"))
        self.demRasterToolButton.setText(_translate("Hillshade", "..."))
        self.okPushButton.setText(_translate("Hillshade", "OK"))
        self.optionsGroupBox.setTitle(_translate("Hillshade", "Options"))
        self.altitudeLabel.setText(_translate("Hillshade", "Altitude"))
        self.azimuthLabel.setText(_translate("Hillshade", "Azimuth"))
        self.zFactorLabel.setText(_translate("Hillshade", "z Factor"))
        self.outputGroupBox.setTitle(_translate("Hillshade", "Output"))
        self.outputRasterLabel.setText(_translate("Hillshade", "Output raster"))
        self.outputRasterToolButton.setText(_translate("Hillshade", "..."))
        self.cancelPushButton.setText(_translate("Hillshade", "Cancel"))
